server:
  port: 8083

spring:
  application:
    name: service-content
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easytiwu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: ${DB_PASSWORD:123456}

logging:
  level:
    com.easytiwu.servicecontent: DEBUG