server:
  port: 8080 # Gateway端口

spring:
  application:
    name: service-gateway

  cloud:
    gateway:
      routes:
        - id: service-auth
          uri: http://localhost:8085 # 认证服务端口
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0

        - id: service-upload
          uri: http://localhost:8084 # 上传服务端口
          predicates:
            - Path=/api/v1/upload/**
          filters:
            - StripPrefix=0

        - id: service-bank
          uri: http://localhost:8081 # 题库服务端口
          predicates:
            - Path=/api/v1/banks/**
          filters:
            - StripPrefix=0

        - id: service-content
          uri: http://localhost:8082 # 内容服务端口
          predicates:
            - Path=/api/v1/content/**
          filters:
            - StripPrefix=0

        - id: service-statistics
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/statistics/**
          filters:
            - StripPrefix=0

      # 全局跨域配置
      globalcors:
        cors-configurations:
          "[/**]":
            # 允许的请求来源
            allowedOrigins:
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
              - "http://0.0.0.0:3000"
              - "http://192.168.18.110:3000"
              - "http://localhost:3002"
            # 允许的HTTP方法
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            # 允许的请求头
            allowedHeaders:
              - "*"
            # 是否允许发送Cookie等凭证信息
            allowCredentials: true
            # 预检请求的有效期（秒）
            maxAge: 3600

      # 默认过滤器
      default-filters:
        - name: Logging
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT
            backoff:
              firstBackoff: 100ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false

# 服务配置
service:
  auth:
    url: http://localhost:8085
  upload:
    url: http://localhost:8084
  bank:
    url: http://localhost:8081
  content:
    url: http://localhost:8082
  statistics:
    url: http://localhost:8083

# Actuator监控端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,logfile
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    com.easytiwu.servicegateway: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
