server:
  port: 8080   # Gateway端口

spring:
  application:
    name: service-gateway

  cloud:
    gateway:
      routes:
        - id: service-upload
          uri: http://localhost:8081   # 上传服务
          predicates:
            - Path=/api/upload/**
          filters:
            - StripPrefix=1

        - id: service-bank
          uri: http://localhost:8082   # 银行服务
          predicates:
            - Path=/api/bank/**
          filters:
            - StripPrefix=1
            
        - id: service-content
          uri: http://localhost:8083   # 内容服务
          predicates:
            - Path=/api/content/**
          filters:
            - StripPrefix=1

      # 全局跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
            allowedMethods: 
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders: 
              - "*"
            allowCredentials: true
            maxAge: 3600
            
      # 默认过滤器
      default-filters:
        - name: Logging
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT
            backoff:
              firstBackoff: 100ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false
            
# 服务配置
service:
  upload:
    url: http://localhost:8081
  bank:
    url: http://localhost:8082
  content:
    url: http://localhost:8083

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    com.easytiwu.servicegateway: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"