spring:
  application:
    name: service-upload
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easytiwu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

server:
  port: 8081

llm:
  service:
    url: http://localhost:8082/api/llm/process

logging:
  level:
    com.easytiwu.serviceupload: DEBUG