spring:
  application:
    name: service-upload
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easytiwu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

server:
  port: 8081

llm:
  service:
    url: https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation
  dashscope:
    api-key: sk-282b5b70ba484626baa755e617b3e7d4

logging:
  level:
    com.easytiwu.serviceupload: DEBUG